### ISSUE TITLE
Add support for Multiverse

### ISSUE THREAD

**Issue by penturt** [Codeski/dynmap-structures#1]
I love the idea of this plugin, and would love to use it, but i don't think its compatible with the latest version of spigot.

i'm using: 
Spigot: git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
Dynmap: dynmap version 2.2-SNAPSHOT-1097

And i'm gettign the following error at server start. http://pastebin.com/sZQh5yw9

**Comment by KovuTheHusky** [comment]
I'll look into this either tomorrow on Monday. Thanks for the bug report!

**Comment by penturt** [comment]
Awesome,  thank for the quick reply.

**Comment by KovuTheHusky** [comment]
Are you using a multi-world plugin like Multiverse? Or anything that would change the name of your world from the default?

**Comment by penturt** [comment]
Oh yeah i use multiverse, an my main worlds dont use defualt names at anymore.

**Comment by penturt** [comment]
And*

**Comment by KovuTheHusky** [comment]
I'll see what I can do - thanks for the help!

**Comment by penturt** [comment]
No thankyou. This would great for my factions server.

**Comment by KovuTheHusky** [comment]
I seem to have this working. If you wouldn't mind testing it before I publish it, that would be greatly appreciated. You can grab the latest build from here. http://hub.codeski.com/jenkins/job/dynmap-structures/

**Comment by penturt** [comment]
ok i'll test it shortly

**Comment by penturt** [comment]
Turned it on, seems to be working just fine. loaded without an issue, dynmap markers are work all looks good.

one thing i had to do was add "depend: [ dynmap ]" to the plugin.yml so that it would load in the correct order for me. other than that it all seems great.

thanks for the quick turn around.

**Comment by KovuTheHusky** [comment]
I forgot about that, I've added that in the next build. I'll clean up some of my code and hopefully have an official release here and on BukkitDev soon. Thanks again!
