### ISSUE TITLE
Unable to read Stronghold.dat due to EOFException

### ISSUE THREAD

**Issue by tonyj4life** [Codeski/dynmap-structures#4]
Sorry for bothering you i don't mean to be a nuisance but i have this error code, more like warning code and don't really know what it means or whether or not its an issue i should address and or whether or not it can be avoided or fix, preferably fixed.. ONce again i apologize for bother i like this plugin a lot and thank you for taking your time to read this and making this plugin possible.

8/30/2015 7:38:22 PM [INFO] [dynmap-structures] Updating markers for world 'XCLAN'.
8/30/2015 7:38:22 PM [INFO] [dynmap-structures] Updating: Stronghold.dat
8/30/2015 7:38:23 PM [WARNING] java.io.EOFException: Unexpected end of ZLIB input stream
8/30/2015 7:38:23 PM [WARNING] 	at java.util.zip.InflaterInputStream.fill(Unknown Source)
8/30/2015 7:38:23 PM [WARNING] 	at java.util.zip.InflaterInputStream.read(Unknown Source)
8/30/2015 7:38:23 PM [WARNING] 	at java.util.zip.GZIPInputStream.read(Unknown Source)
8/30/2015 7:38:23 PM [WARNING] 	at java.util.zip.InflaterInputStream.read(Unknown Source)
8/30/2015 7:38:23 PM [WARNING] 	at java.io.DataInputStream.readByte(Unknown Source)
8/30/2015 7:38:23 PM [WARNING] 	at com.codeski.nbt.NBTReader.readTag(NBTReader.java:113)
8/30/2015 7:38:23 PM [WARNING] 	at com.codeski.nbt.NBTReader.read(NBTReader.java:36)
8/30/2015 7:38:23 PM [WARNING] 	at com.codeski.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.update(DynmapStructuresPlugin.java:92)
8/30/2015 7:38:23 PM [WARNING] 	at com.codeski.dynmap.structures.DynmapStructuresPlugin$DynmapStructuresRunnable.run(DynmapStructuresPlugin.java:72)
8/30/2015 7:38:23 PM [WARNING] 	at java.lang.Thread.run(Unknown Source)

**Comment by KovuTheHusky** [comment]
Would it be possible for you to upload your Stronghold.dat file?

**Comment by tonyj4life** [comment]
how could i upload the file as an attachment i don't see the option for it...

**Comment by tonyj4life** [comment]
Date: Sun, 30 Aug 2015 20:03:18 -0700

**Comment by KovuTheHusky** [comment]
That didn't work - you could upload it to any service. Personally I'd recommend [Mega](https://mega.nz/). You just drag your file in and then once it's uploaded you can click the arrow on the right side of the page and select "get link" to share it. If that's too much trouble you could [email](mailto:kovuthehusky@gmail.com) it.

**Comment by tonyj4life** [comment]
sent an email from antonio-oturan@hotmail.com

**Comment by KovuTheHusky** [comment]
Got it, I'll take a look when I get a chance. Thanks!

**Comment by tonyj4life** [comment]
no thank you

Date: Thu, 3 Sep 2015 15:04:02 -0700

**Comment by KovuTheHusky** [comment]
The file appears to be fine. I loaded it up in my own server and it read it just fine. What version of CraftBukkit/Spigot are you using? What version of dynmap? What version of dynmap-structures?

**Comment by tonyj4life** [comment]
latest on everything spigot 1.8.8, and latest on dynmap structures, but when you had originally asked for the stronghold.dat file, i was running spigot 1.8.0

Date: Fri, 4 Sep 2015 14:57:18 -0700

**Comment by KovuTheHusky** [comment]
I tried running on Spigot instead of CraftBukkit and it still read the file fine. I'm not really sure why you're having this problem. Unless you want to send me your whole Spigot directory (minus the world chunk files if you want to save space) I'm not sure what else I can do. Let me know what you want to do.

**Comment by tonyj4life** [comment]
WELL SINCE I UPDATED TO THE 1.8.8 version of spigot from 1.8.0. And started a new world I haven't came accross the issue again.. Which I think may have fixed it due to the fact that you mentioned whether I UPDATED my version of spigot. So I think you solved this case of mines. I didn't even think my spigot was out of date till you mention if I was fully updated. Thank you


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by KovuTheHusky** [comment]
Let me know if you have the problem again! Glad it worked out.
