### ISSUE TITLE
all cores at 100% when using dynmap-structures.

### ISSUE THREAD

**Issue by Thierry76be** [Codeski/dynmap-structures#5]
Hello,

I tried the plugin on bukkit 1.8.8R0.1-SNAPSHOT with a pre-generated world wit a radius of 10000 (using worldborder). After starting the server it will start running at 100% on all cores within a minute.

I am running the next plugings (33): Stables, GroupManager, WorldEdit, FrameProtect, Vault, PlotMe, Prism, WorldGuard, dynmap, DynmapPlotMe, Chairs, Recycler, PaintWar, Lockette, Sleep, MiningTNT, PlotMe-DefaultGenerator, PunchWood, Essentials, Citizens, Jobs, WorldBorder, EssentialsSpawn, Multiverse-Core, dtlTraders, Sentry, pvparena, LimitedCreative, CompatNoCheatPlus, ChestShop, NoCheatPlus, Multiverse-Portals, Multiverse-NetherPortals

and OpenJDK Runtime Environment (IcedTea 2.6.1) (7u85-2.6.1-5ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode) on Ubuntu 14.04 64bit with all updates

Can you help me diagnose the problem? is it the size of the world or might there be an other problem?

Best regards,
Thierry.

**Comment by KovuTheHusky** [comment]
Could be the size of the world, specifically because that increases the file size for all the structure's NBT .dat files. Which version of the plugin are you using and which structures do you have enabled in the dynmap-structures config.yml? I'll do a few tests after you get back to me and see what I can do.

**Comment by Thierry76be** [comment]
The size of the world is 5.8GB and I use version dynmap-structures-0.1.3-all.jar. It takes a few minutes to happen or maybe a player has to start playing on the server. It also looks like the map is complete, it shows structures until the world border, but maybe it starts updating the map?

![dynmap-structures_and_border](https://cloud.githubusercontent.com/assets/15850751/11168121/88653006-8b82-11e5-86c0-a397da900ae9.png)

Here 
is my config file:
structures:
  fortress: true
  mineshaft: false
  monument: true
  stronghold: false
  temple: true
  witch: true
  village: true
layer:
  name: Structures
  hidebydefault: false
  layerprio: 10
  nolabels: false
  minzoom: 0

Thanks for having a look at it, it would be a really nice addition to our server. :)

**Comment by Thierry76be** [comment]
I have removed all plugins, except dynmap and dynmap-structures. It looked better, but only after a minute or two one core stayed at 100% again, the other core was between 30 en 40%, even when nobody was online. I had hoped it was only in combination with an other plugin, that I might have could done without.

Let me know if there is something else I can test for you.

**Comment by KovuTheHusky** [comment]
I haven't had time to look into this yet, though I should in a day or two. Just want to make sure; dynmap isn't generating tiles, right? dynmap-structures should only ever be using CPU on startup (to read the structures files once) and whenever the structures files are changed (generally from new chunks with structures in them are being generated and written to disk).

**Comment by KovuTheHusky** [comment]
I should have a new version out with a fix soon!

I made a mistake with the file watcher - I had never used it before and I had a line out of a loop when it should have been inside.

Thank you so much for reporting this problem!

**Comment by KovuTheHusky** [comment]
Closed by commit/77c4d0d94de3ca5f5768fd1c2132be5384055801.

**Comment by KovuTheHusky** [comment]
The new version should be available on dev.bukkit.org shortly.

**Comment by Thierry76be** [comment]
Thank you for the quick fix. I have tested it on my server and it runs great now.
With some luck I can get the kids to dos some more exploring now. :)
