### ISSUE TITLE
Add support for Biomes O Plenty on Forge versions < 1.7.10

### ISSUE THREAD

**Issue by TroyMLP** [Codeski/dynmap-structures#6]
As is, the plugin(dynmap-structures-0.1.4-all.jar) seems to function with Dynmap(Dynmap-2.1-forge-1.6.4.jar) On my MCPC+ Server(MCPC-Plus-164-251) at the moment however several things are missing. Primarily I am looking for Villages to show up so I have a 2 part question, including notes..

1. I notice that withing the configuration and jar itself it is looking for a file "Village.dat" where as my server is "villages.dat" for some reason. I assume that this is the reason that the vanilla villages are not showing on the map as a marker.

2. I am running Biomes O Plenty and it seems that they generate and handle "BOPVillage.dat", is there a way to add this so that BOP Villages show on the map with markers too?

**Comment by KovuTheHusky** [comment]
The villages.dat file is unrelated. It does not store the location of villages. I'll look into MCPC and Biomes O Plenty support in the next few days.

**Comment by TroyMLP** [comment]
Roger, thanks Boss!

**Comment by KovuTheHusky** [comment]
Where is MCPC+/Cauldron able to be downloaded? Every page I find from searching the web is a 404 now.

**Comment by TroyMLP** [comment]
If you have an email address I'll send you the one I have. I've no idea why they are unobtainable elsewhere, I just had it on my pc from 4 months ago when I got it from a previous game server provider I had.

**Comment by TroyMLP** [comment]
Edit: just googled mcpc+ 1.6.4 release and got it on first result http://tcpr.ca/files/mcpc/mcpc-plus-1.6.4-R2.1-forge965-B243.jar

**Comment by TroyMLP** [comment]
Or http://tcpr.ca/files/mcpc/mcpc-plus-1.6.4-R2.1-forge965-B251.jar for the build version I have..

Sorry about double posts, on mobile and cannot edit

**Comment by KovuTheHusky** [comment]
The first step for me is to port Dynmap-Structures to Forge - the CraftBukkit Dynmap-Structures won't work with Dynmap Forge. I might get to this in the next few days, but if not it'll have to wait until after the holidays. After that's done I'll look into compatibility with Biomes O Plenty.

**Comment by TroyMLP** [comment]
Thanks again!

**Comment by KovuTheHusky** [comment]
Actually, after playing around with MCPC+ and Cauldron a bit, it seems to work fine with DynmapCBBridge installed. I've tested with mcpc-plus-1.6.4-R2.1-forge965-B243 running Dynmap-2.1-forge-1.6.4 and BiomesOPlenty-universal-1.6.4-1.2.1.434 and it seems to work just fine. I don't have a BOPVillage.dat anywhere though, even after using WorldBorder to generate chunks out to a radius of 2048 blocks.

Are you using a different, possibly older, version of Biomes O Plenty? Where does it create the file, in the same data directory as all of the other *.dat files?

**Comment by KovuTheHusky** [comment]
Got it, ignore everything I said. Working on fixing this now.

**Comment by KovuTheHusky** [comment]
Closed by afe6c0f9eecd04151c1e4241e041e6f869328855.

Download should be available on BukkitDev shortly:
http://dev.bukkit.org/bukkit-plugins/dynmap-structures/files/4-0-1-5/

**Comment by KovuTheHusky** [comment]
Let me know if you have any issues with the new version! Thanks again for the report!
